FROM python:3.11-slim

#Environment variables
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 

#Install system dependancies for ML libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    libgomp1 \
    libssl-dev \
    git \
    && rm -rf /var/lib/apt/lists/*


#working directory
WORKDIR /project

#Coping project files
COPY . .

#Upgrading pip and install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["kedro", "run"]
